// Auto-generated by `supabase gen types --local` — do not edit manually.
// Re-run `bun run db:types` in apps/backend to refresh.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
	graphql_public: {
		Tables: { [_ in never]: never };
		Views: { [_ in never]: never };
		Functions: {
			graphql: {
				Args: { extensions?: Json; operationName?: string; query?: string; variables?: Json };
				Returns: Json;
			};
		};
		Enums: { [_ in never]: never };
		CompositeTypes: { [_ in never]: never };
	};
	public: {
		Tables: {
			BibleBook: {
				Row: {
					commonName: string | null;
					englishName: string | null;
					id: string | null;
					isApocryphal: string | null;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					numberOfChapters: number | null;
					order: number | null;
					sha256: string | null;
					shortName: string | null;
					textDirection: string;
					title: string | null;
					translationId: string | null;
					uuid: string;
					website: string | null;
				};
				Insert: {
					commonName?: string | null;
					englishName?: string | null;
					id?: string | null;
					isApocryphal?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					numberOfChapters?: number | null;
					order?: number | null;
					sha256?: string | null;
					shortName?: string | null;
					textDirection: string;
					title?: string | null;
					translationId?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Update: {
					commonName?: string | null;
					englishName?: string | null;
					id?: string | null;
					isApocryphal?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					numberOfChapters?: number | null;
					order?: number | null;
					sha256?: string | null;
					shortName?: string | null;
					textDirection?: string;
					title?: string | null;
					translationId?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Relationships: [];
			};
			BibleChapter: {
				Row: {
					bookId: string | null;
					englishName: string | null;
					id: string | null;
					json: string | null;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					number: number | null;
					sha256: string | null;
					shortName: string | null;
					textDirection: string | null;
					translationId: string | null;
					uuid: string;
					website: string | null;
				};
				Insert: {
					bookId?: string | null;
					englishName?: string | null;
					id?: string | null;
					json?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					number?: number | null;
					sha256?: string | null;
					shortName?: string | null;
					textDirection?: string | null;
					translationId?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Update: {
					bookId?: string | null;
					englishName?: string | null;
					id?: string | null;
					json?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					number?: number | null;
					sha256?: string | null;
					shortName?: string | null;
					textDirection?: string | null;
					translationId?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Relationships: [];
			};
			BibleChapterAudioUrl: {
				Row: {
					bookId: string | null;
					englishName: string | null;
					id: string | null;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					number: number | null;
					reader: string | null;
					sha256: string | null;
					shortName: string | null;
					textDirection: string | null;
					translationId: string | null;
					url: string | null;
					uuid: string;
					website: string | null;
				};
				Insert: {
					bookId?: string | null;
					englishName?: string | null;
					id?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					number?: number | null;
					reader?: string | null;
					sha256?: string | null;
					shortName?: string | null;
					textDirection?: string | null;
					translationId?: string | null;
					url?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Update: {
					bookId?: string | null;
					englishName?: string | null;
					id?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					number?: number | null;
					reader?: string | null;
					sha256?: string | null;
					shortName?: string | null;
					textDirection?: string | null;
					translationId?: string | null;
					url?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Relationships: [];
			};
			ChapterFootnote: {
				Row: {
					bookId: string | null;
					chapterNumber: number | null;
					englishName: string | null;
					id: number | null;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					sha256: string | null;
					shortName: string | null;
					text: string | null;
					textDirection: string | null;
					translationId: string | null;
					uuid: string;
					verseNumber: number | null;
					website: string | null;
				};
				Insert: {
					bookId?: string | null;
					chapterNumber?: number | null;
					englishName?: string | null;
					id?: number | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					sha256?: string | null;
					shortName?: string | null;
					text?: string | null;
					textDirection?: string | null;
					translationId?: string | null;
					uuid?: string;
					verseNumber?: number | null;
					website?: string | null;
				};
				Update: {
					bookId?: string | null;
					chapterNumber?: number | null;
					englishName?: string | null;
					id?: number | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					sha256?: string | null;
					shortName?: string | null;
					text?: string | null;
					textDirection?: string | null;
					translationId?: string | null;
					uuid?: string;
					verseNumber?: number | null;
					website?: string | null;
				};
				Relationships: [];
			};
			ChapterVerse: {
				Row: {
					bookId: string | null;
					chapterNumber: number | null;
					contentJson: string | null;
					englishName: string | null;
					id: string | null;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					number: number | null;
					sha256: string | null;
					shortName: string | null;
					text: string | null;
					textDirection: string | null;
					translationId: string | null;
					uuid: string;
					website: string | null;
				};
				Insert: {
					bookId?: string | null;
					chapterNumber?: number | null;
					contentJson?: string | null;
					englishName?: string | null;
					id?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					number?: number | null;
					sha256?: string | null;
					shortName?: string | null;
					text?: string | null;
					textDirection?: string | null;
					translationId?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Update: {
					bookId?: string | null;
					chapterNumber?: number | null;
					contentJson?: string | null;
					englishName?: string | null;
					id?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					number?: number | null;
					sha256?: string | null;
					shortName?: string | null;
					text?: string | null;
					textDirection?: string | null;
					translationId?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Relationships: [];
			};
			Commentary: {
				Row: {
					englishName: string | null;
					id: string;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					sha256: string | null;
					textDirection: string | null;
					uuid: string;
					website: string | null;
				};
				Insert: {
					englishName?: string | null;
					id: string;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Update: {
					englishName?: string | null;
					id?: string;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Relationships: [];
			};
			CommentaryBook: {
				Row: {
					commentaryId: string | null;
					commonName: string | null;
					englishName: string | null;
					id: string;
					introduction: string | null;
					introductionSummary: string | null;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					numberOfChapters: number | null;
					order: number | null;
					sha256: string | null;
					textDirection: string | null;
					uuid: string;
					website: string | null;
				};
				Insert: {
					commentaryId?: string | null;
					commonName?: string | null;
					englishName?: string | null;
					id: string;
					introduction?: string | null;
					introductionSummary?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					numberOfChapters?: number | null;
					order?: number | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Update: {
					commentaryId?: string | null;
					commonName?: string | null;
					englishName?: string | null;
					id?: string;
					introduction?: string | null;
					introductionSummary?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					numberOfChapters?: number | null;
					order?: number | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Relationships: [];
			};
			CommentaryChapter: {
				Row: {
					bookId: string | null;
					commentaryId: string | null;
					englishName: string | null;
					id: string;
					introduction: string | null;
					json: string | null;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					number: number | null;
					sha256: string | null;
					textDirection: string | null;
					uuid: string;
					website: string | null;
				};
				Insert: {
					bookId?: string | null;
					commentaryId?: string | null;
					englishName?: string | null;
					id: string;
					introduction?: string | null;
					json?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					number?: number | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Update: {
					bookId?: string | null;
					commentaryId?: string | null;
					englishName?: string | null;
					id?: string;
					introduction?: string | null;
					json?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					number?: number | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Relationships: [];
			};
			CommentaryChapterVerse: {
				Row: {
					bookId: string | null;
					chapterNumber: number | null;
					commentaryId: string | null;
					contentJson: string | null;
					englishName: string | null;
					id: string | null;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					number: number | null;
					sha256: string | null;
					text: string | null;
					textDirection: string | null;
					uuid: string;
					website: string | null;
				};
				Insert: {
					bookId?: string | null;
					chapterNumber?: number | null;
					commentaryId?: string | null;
					contentJson?: string | null;
					englishName?: string | null;
					id?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					number?: number | null;
					sha256?: string | null;
					text?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Update: {
					bookId?: string | null;
					chapterNumber?: number | null;
					commentaryId?: string | null;
					contentJson?: string | null;
					englishName?: string | null;
					id?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					number?: number | null;
					sha256?: string | null;
					text?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Relationships: [];
			};
			CommentaryProfile: {
				Row: { referenceid: number | null; subject: string | null; uuid: string; uuid_old: number };
				Insert: {
					referenceid?: number | null;
					subject?: string | null;
					uuid?: string;
					uuid_old?: number;
				};
				Update: {
					referenceid?: number | null;
					subject?: string | null;
					uuid?: string;
					uuid_old?: number;
				};
				Relationships: [];
			};
			CommentaryProfileContent: {
				Row: {
					commentaryid: number | null;
					content: string | null;
					profileid: number | null;
					uuid: string;
					uuid_old: number;
				};
				Insert: {
					commentaryid?: number | null;
					content?: string | null;
					profileid?: number | null;
					uuid?: string;
					uuid_old?: number;
				};
				Update: {
					commentaryid?: number | null;
					content?: string | null;
					profileid?: number | null;
					uuid?: string;
					uuid_old?: number;
				};
				Relationships: [];
			};
			CrossReference: {
				Row: {
					book: number | null;
					book_to: number | null;
					chapter: number | null;
					chapter_to: number | null;
					uuid: string;
					verse: number | null;
					verse_end: number | null;
					verse_to_end: string | null;
					verse_to_start: number | null;
					verseId: number | null;
					votes: string | null;
				};
				Insert: {
					book?: number | null;
					book_to?: number | null;
					chapter?: number | null;
					chapter_to?: number | null;
					uuid?: string;
					verse?: number | null;
					verse_end?: number | null;
					verse_to_end?: string | null;
					verse_to_start?: number | null;
					verseId?: number | null;
					votes?: string | null;
				};
				Update: {
					book?: number | null;
					book_to?: number | null;
					chapter?: number | null;
					chapter_to?: number | null;
					uuid?: string;
					verse?: number | null;
					verse_end?: number | null;
					verse_to_end?: string | null;
					verse_to_start?: number | null;
					verseId?: number | null;
					votes?: string | null;
				};
				Relationships: [];
			};
			Dataset: {
				Row: {
					englishName: string | null;
					id: string;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					sha256: string | null;
					textDirection: string | null;
					uuid: string;
					website: string | null;
				};
				Insert: {
					englishName?: string | null;
					id: string;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Update: {
					englishName?: string | null;
					id?: string;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Relationships: [];
			};
			DatasetBook: {
				Row: {
					datasetId: string | null;
					englishName: string | null;
					id: string;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					numberOfChapters: number | null;
					order: number | null;
					sha256: string | null;
					textDirection: string | null;
					uuid: string;
					website: string | null;
				};
				Insert: {
					datasetId?: string | null;
					englishName?: string | null;
					id: string;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					numberOfChapters?: number | null;
					order?: number | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Update: {
					datasetId?: string | null;
					englishName?: string | null;
					id?: string;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					numberOfChapters?: number | null;
					order?: number | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Relationships: [];
			};
			DatasetChapter: {
				Row: {
					bookId: string | null;
					datasetId: string | null;
					englishName: string | null;
					id: string;
					json: string | null;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					number: number | null;
					sha256: string | null;
					textDirection: string | null;
					uuid: string;
					website: string | null;
				};
				Insert: {
					bookId?: string | null;
					datasetId?: string | null;
					englishName?: string | null;
					id: string;
					json?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					number?: number | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Update: {
					bookId?: string | null;
					datasetId?: string | null;
					englishName?: string | null;
					id?: string;
					json?: string | null;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					number?: number | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Relationships: [];
			};
			DatasetChapterVerse: {
				Row: {
					bookId: string | null;
					chapterNumber: number | null;
					contentJson: string | null;
					datasetId: string | null;
					englishName: string | null;
					id: string;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					number: number | null;
					sha256: string | null;
					textDirection: string | null;
					uuid: string;
					website: string | null;
				};
				Insert: {
					bookId?: string | null;
					chapterNumber?: number | null;
					contentJson?: string | null;
					datasetId?: string | null;
					englishName?: string | null;
					id: string;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					number?: number | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Update: {
					bookId?: string | null;
					chapterNumber?: number | null;
					contentJson?: string | null;
					datasetId?: string | null;
					englishName?: string | null;
					id?: string;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					number?: number | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Relationships: [];
			};
			DatasetReference: {
				Row: {
					bookId: string | null;
					chapterNumber: number | null;
					datasetId: string | null;
					endVerseNumber: number | null;
					englishName: string | null;
					id: number;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					referenceBookId: string | null;
					referenceChapter: number | null;
					referenceVerse: number | null;
					score: number | null;
					sha256: string | null;
					textDirection: string | null;
					uuid: string;
					verseNumber: number | null;
					website: string | null;
				};
				Insert: {
					bookId?: string | null;
					chapterNumber?: number | null;
					datasetId?: string | null;
					endVerseNumber?: number | null;
					englishName?: string | null;
					id: number;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					referenceBookId?: string | null;
					referenceChapter?: number | null;
					referenceVerse?: number | null;
					score?: number | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					verseNumber?: number | null;
					website?: string | null;
				};
				Update: {
					bookId?: string | null;
					chapterNumber?: number | null;
					datasetId?: string | null;
					endVerseNumber?: number | null;
					englishName?: string | null;
					id?: number;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					referenceBookId?: string | null;
					referenceChapter?: number | null;
					referenceVerse?: number | null;
					score?: number | null;
					sha256?: string | null;
					textDirection?: string | null;
					uuid?: string;
					verseNumber?: number | null;
					website?: string | null;
				};
				Relationships: [];
			};
			Dictionary: {
				Row: {
					definition: string | null;
					id: string;
					lexeme: string | null;
					pronunciation: string | null;
					short_definition: string | null;
					topic: string | null;
					transliteration: string | null;
					uuid: string;
				};
				Insert: {
					definition?: string | null;
					id?: string;
					lexeme?: string | null;
					pronunciation?: string | null;
					short_definition?: string | null;
					topic?: string | null;
					transliteration?: string | null;
					uuid?: string;
				};
				Update: {
					definition?: string | null;
					id?: string;
					lexeme?: string | null;
					pronunciation?: string | null;
					short_definition?: string | null;
					topic?: string | null;
					transliteration?: string | null;
					uuid?: string;
				};
				Relationships: [];
			};
			Translation: {
				Row: {
					englishName: string | null;
					id: string;
					language: string | null;
					licenseNotes: string | null;
					licenseUrl: string | null;
					name: string | null;
					sha256: string | null;
					shortName: string | null;
					textDirection: string | null;
					uuid: string;
					website: string | null;
				};
				Insert: {
					englishName?: string | null;
					id: string;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					sha256?: string | null;
					shortName?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Update: {
					englishName?: string | null;
					id?: string;
					language?: string | null;
					licenseNotes?: string | null;
					licenseUrl?: string | null;
					name?: string | null;
					sha256?: string | null;
					shortName?: string | null;
					textDirection?: string | null;
					uuid?: string;
					website?: string | null;
				};
				Relationships: [];
			};
			// library_books tables — from migration 20260413000000
			library_books: {
				Row: {
					uuid: string;
					slug: string;
					title: string;
					subtitle: string | null;
					authors: Json | null;
					publisher: string | null;
					published_date: string | null;
					language: string;
					text_direction: string;
					category: LibraryBookCategory;
					subjects: Json | null;
					source_type: LibraryBookSourceType;
					source_uri: string | null;
					cover_url: string | null;
					description: string | null;
					website: string | null;
					license: string | null;
					license_url: string | null;
					total_sections: number;
					total_pages: number;
					extra: Json | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					uuid?: string;
					slug: string;
					title: string;
					subtitle?: string | null;
					authors?: Json | null;
					publisher?: string | null;
					published_date?: string | null;
					language?: string;
					text_direction?: string;
					category?: LibraryBookCategory;
					subjects?: Json | null;
					source_type?: LibraryBookSourceType;
					source_uri?: string | null;
					cover_url?: string | null;
					description?: string | null;
					website?: string | null;
					license?: string | null;
					license_url?: string | null;
					total_sections?: number;
					total_pages?: number;
					extra?: Json | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					uuid?: string;
					slug?: string;
					title?: string;
					subtitle?: string | null;
					authors?: Json | null;
					publisher?: string | null;
					published_date?: string | null;
					language?: string;
					text_direction?: string;
					category?: LibraryBookCategory;
					subjects?: Json | null;
					source_type?: LibraryBookSourceType;
					source_uri?: string | null;
					cover_url?: string | null;
					description?: string | null;
					website?: string | null;
					license?: string | null;
					license_url?: string | null;
					total_sections?: number;
					total_pages?: number;
					extra?: Json | null;
					created_at?: string;
					updated_at?: string;
				};
				Relationships: [];
			};
			book_sections: {
				Row: {
					uuid: string;
					book_uuid: string;
					parent_uuid: string | null;
					title: string | null;
					section_type: BookSectionType;
					level: number;
					order: number;
					total_pages: number;
					extra: Json | null;
				};
				Insert: {
					uuid?: string;
					book_uuid: string;
					parent_uuid?: string | null;
					title?: string | null;
					section_type?: BookSectionType;
					level?: number;
					order?: number;
					total_pages?: number;
					extra?: Json | null;
				};
				Update: {
					uuid?: string;
					book_uuid?: string;
					parent_uuid?: string | null;
					title?: string | null;
					section_type?: BookSectionType;
					level?: number;
					order?: number;
					total_pages?: number;
					extra?: Json | null;
				};
				Relationships: [
					{
						foreignKeyName: "book_sections_book_uuid_fkey";
						columns: ["book_uuid"];
						referencedRelation: "library_books";
						referencedColumns: ["uuid"];
					},
					{
						foreignKeyName: "book_sections_parent_uuid_fkey";
						columns: ["parent_uuid"];
						referencedRelation: "book_sections";
						referencedColumns: ["uuid"];
					},
				];
			};
			book_pages: {
				Row: {
					uuid: string;
					book_uuid: string;
					section_uuid: string | null;
					title: string | null;
					book_index: number;
					section_index: number;
					html: string | null;
					text: string | null;
					extra: Json | null;
				};
				Insert: {
					uuid?: string;
					book_uuid: string;
					section_uuid?: string | null;
					title?: string | null;
					book_index?: number;
					section_index?: number;
					html?: string | null;
					text?: string | null;
					extra?: Json | null;
				};
				Update: {
					uuid?: string;
					book_uuid?: string;
					section_uuid?: string | null;
					title?: string | null;
					book_index?: number;
					section_index?: number;
					html?: string | null;
					text?: string | null;
					extra?: Json | null;
				};
				Relationships: [
					{
						foreignKeyName: "book_pages_book_uuid_fkey";
						columns: ["book_uuid"];
						referencedRelation: "library_books";
						referencedColumns: ["uuid"];
					},
					{
						foreignKeyName: "book_pages_section_uuid_fkey";
						columns: ["section_uuid"];
						referencedRelation: "book_sections";
						referencedColumns: ["uuid"];
					},
				];
			};
		};
		Views: { [_ in never]: never };
		Functions: { [_ in never]: never };
		Enums: {
			book_category: LibraryBookCategory;
			book_section_type: BookSectionType;
			book_source_type: LibraryBookSourceType;
		};
		CompositeTypes: { [_ in never]: never };
	};
};

// ── Enum types (mirrors Python enums in app/models/book.py) ──────────────────

export type LibraryBookCategory =
	| "bible"
	| "quran"
	| "tanakh"
	| "commentary"
	| "lexicon"
	| "dictionary"
	| "devotional"
	| "theology"
	| "history"
	| "philosophy"
	| "fiction"
	| "other";

export type LibraryBookSourceType = "epub" | "pdf" | "url" | "manual";

export type BookSectionType =
	| "part"
	| "chapter"
	| "section"
	| "article"
	| "entry"
	| "appendix"
	| "introduction"
	| "preface"
	| "foreword"
	| "index"
	| "glossary"
	| "other";

// ── Generic helper types (mirrors Supabase client helper types) ───────────────

type PublicSchema = Database["public"];

export type Tables<T extends keyof PublicSchema["Tables"]> =
	PublicSchema["Tables"][T]["Row"];

export type TablesInsert<T extends keyof PublicSchema["Tables"]> =
	PublicSchema["Tables"][T]["Insert"];

export type TablesUpdate<T extends keyof PublicSchema["Tables"]> =
	PublicSchema["Tables"][T]["Update"];
