/**
 * @biblepedia/ui - React Spectrum S2 Component Library
 *
 * This package re-exports React Spectrum S2 components for use in the Livrea app.
 * It provides a centralized location for UI components and allows for custom
 * component extensions when needed.
 */

// Re-export types
export type {
	AccordionItemHeaderProps,
	AccordionItemPanelProps,
	AccordionItemProps,
	AccordionItemTitleProps,
	AccordionProps,
	// Layout
	ActionBarProps,
	// Button Groups
	ActionButtonGroupProps,
	ActionButtonProps,
	ActionMenuProps,
	AlertDialogProps,
	AssetCardProps,
	AvatarGroupProps,
	// Content
	AvatarProps,
	BadgeProps,
	BreadcrumbProps,
	BreadcrumbsProps,
	ButtonGroupProps,
	// Buttons
	ButtonProps,
	CalendarProps,
	CardPreviewProps,
	CardProps,
	CardViewProps,
	CheckboxGroupProps,
	CheckboxProps,
	CloseButtonProps,
	Color,
	// Color
	ColorAreaProps,
	ColorFieldProps,
	ColorSliderProps,
	ColorSwatchPickerProps,
	ColorSwatchProps,
	ColorWheelProps,
	ComboBoxItemProps,
	ComboBoxProps,
	ComboBoxSectionProps,
	ContextualHelpProps,
	CustomDialogProps,
	// Date & Time
	DateFieldProps,
	DatePickerProps,
	DateRangePickerProps,
	DialogContainerProps,
	// Overlays
	DialogProps,
	DialogTriggerProps,
	DisclosurePanelProps,
	DisclosureProps,
	DividerProps,
	DropZoneProps,
	// Shared types from react-aria-components
	FileTriggerProps,
	// Forms
	FormProps,
	FullscreenDialogProps,
	IconContextValue,
	// Icons and Illustrations
	IconProps,
	IllustrationContextValue,
	IllustrationProps,
	ImageCoordinatorProps,
	ImageProps,
	InlineAlertProps,
	Key,
	LinkButtonProps,
	LinkProps,
	ListViewItemProps,
	ListViewProps,
	MenuItemProps,
	// Collections
	MenuProps,
	MenuSectionProps,
	MenuTriggerProps,
	MeterProps,
	PickerItemProps,
	PickerProps,
	PickerSectionProps,
	PopoverProps,
	ProductCardProps,
	// Status
	ProgressBarProps,
	ProgressCircleProps,
	// Provider
	ProviderProps,
	RadioGroupProps,
	RadioProps,
	RangeCalendarProps,
	RangeSliderProps,
	SearchFieldProps,
	SegmentedControlItemProps,
	SegmentedControlProps,
	Selection,
	SkeletonProps,
	SliderProps,
	SortDescriptor,
	StatusLightProps,
	SubmenuTriggerProps,
	SwitchProps,
	TabListProps,
	TableViewProps,
	TabPanelProps,
	TabProps,
	// Navigation
	TabsProps,
	TagGroupProps,
	TagProps,
	TextAreaProps,
	TextFieldProps,
	TimeFieldProps,
	ToggleButtonGroupProps,
	ToggleButtonProps,
	TooltipProps,
	TooltipTriggerProps,
	TooltipTriggerProps as TooltipTriggerComponentProps,
	UserCardProps,
} from "@react-spectrum/s2";
// Re-export all React Spectrum S2 components
export {
	Accordion,
	AccordionItem,
	AccordionItemHeader,
	AccordionItemPanel,
	AccordionItemTitle,
	// Layout
	ActionBar,
	ActionButton,
	// Button Groups
	ActionButtonGroup,
	ActionMenu,
	AlertDialog,
	AssetCard,
	// Content
	Avatar,
	AvatarGroup,
	Badge,
	Breadcrumbs,
	// Buttons
	Button,
	ButtonGroup,
	Calendar,
	Card,
	CardPreview,
	CardView,
	Cell,
	Checkbox,
	CheckboxGroup,
	CloseButton,
	// Collections helpers
	Collection,
	// Color
	ColorArea,
	ColorField,
	ColorSlider,
	ColorSwatch,
	ColorSwatchPicker,
	ColorWheel,
	Column,
	ComboBox,
	ComboBoxItem,
	ComboBoxSection,
	Content,
	ContextualHelp,
	CustomDialog,
	// Date & Time
	DateField,
	DatePicker,
	DateRangePicker,
	// Overlays
	Dialog,
	DialogContainer,
	DialogTrigger,
	Disclosure,
	DisclosurePanel,
	DisclosureTitle,
	Divider,
	DropZone,
	Footer,
	// Forms
	Form,
	FullscreenDialog,
	Header,
	Heading,
	IllustratedMessage,
	Image,
	ImageCoordinator,
	InlineAlert,
	Keyboard,
	Link,
	LinkButton,
	ListView,
	ListViewItem,
	// Collections
	Menu,
	MenuItem,
	MenuSection,
	MenuTrigger,
	Meter,
	NumberField,
	Picker,
	PickerItem,
	PickerSection,
	Popover,
	ProductCard,
	// Status
	ProgressBar,
	ProgressCircle,
	// Provider
	Provider,
	Radio,
	RadioGroup,
	RangeCalendar,
	RangeSlider,
	Row,
	SearchField,
	SegmentedControl,
	SegmentedControlItem,
	SelectBox,
	// Selection helpers
	SelectBoxGroup,
	Skeleton,
	Slider,
	StatusLight,
	SubmenuTrigger,
	Switch,
	Tab,
	TabList,
	TableBody,
	TableHeader,
	TableView,
	TabPanel,
	// Navigation
	Tabs,
	Tag,
	TagGroup,
	Text,
	TextArea,
	TextField,
	TimeField,
	ToastContainer,
	// Toast
	ToastQueue,
	ToggleButton,
	ToggleButtonGroup,
	Tooltip,
	TooltipTrigger,
	TreeView,
	TreeViewItem,
	UserCard,
} from "@react-spectrum/s2";

// Export custom components
export { ConfirmDialog, type ConfirmDialogProps } from "./components/dialog";

// Export utility types
export type {
	AsProp,
	BaseComponentProps,
	DisableableProps,
	HTMLProps,
	Icon,
	IconProps as IconSaxProps,
	LIIconName,
	LoadingProps,
	OptionalProps,
	PolymorphicProps,
	RequiredProps,
	Size,
	SizeProps,
	Variant,
	VariantProps,
} from "./types";

export { ALL_ICONS } from "./types";
